namespace SpriteKind {
    export const Protectoion = SpriteKind.create()
    export const Boss = SpriteKind.create()
    export const Chest = SpriteKind.create()
    export const GoodProjectile = SpriteKind.create()
    export const SuperGrem2 = SpriteKind.create()
    export const SuperGrem1 = SpriteKind.create()
}
namespace StatusBarKind {
    export const SheildCooldown = StatusBarKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (JumpCount < JumpStatus) {
        mySprite.vy = -140
        JumpCount += 1
    }
})
function WiseOne () {
    TheWiseOne = sprites.create(img`
        . . . . . . . c c . . . . . . . 
        . . . . . . c 5 c . . . . . . . 
        . . . . c c 5 5 5 c c c . . . . 
        . . c c c c 5 5 5 5 c b c c . . 
        . c b b 5 b 5 5 5 5 b 5 b b c . 
        . c b 5 5 b b 5 5 b b 5 5 b c . 
        . . c 5 5 5 b b b b 5 5 5 f . . 
        . . . f 5 5 5 5 5 5 5 5 f f . . 
        . . . . f e e e f b e e f f . . 
        . . . . f e b b f 1 b f f f . . 
        . . . . f b b b b b b f f . . . 
        . . . . . f e e e e f e e . . . 
        . . . . . f 5 b b e b b e . . . 
        . . . . f 5 5 5 5 e b b e . . . 
        . . . . c b 5 5 5 5 e e . . . . 
        . . . . . f f f f f f . . . . . 
        `, SpriteKind.Player)
    tiles.placeOnTile(TheWiseOne, tiles.getTileLocation(31, 28))
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (true) {
        Shield = sprites.create(img`
            . . f f f . . 
            . f 8 8 8 f . 
            . f 8 8 8 f . 
            . f 8 9 8 f . 
            f 8 8 8 9 8 f 
            f 8 8 8 9 8 f 
            f 8 8 8 8 8 f 
            f 8 8 8 8 8 f 
            f 8 8 8 8 8 f 
            f 8 8 8 8 8 f 
            . f 8 8 8 f . 
            . f 8 8 8 f . 
            . f 8 8 8 f . 
            . . f f f . . 
            `, SpriteKind.Protectoion)
        Shield.setPosition(mySprite.x + 13, mySprite.y)
        SheildCreated = true
    }
})
sprites.onOverlap(SpriteKind.SuperGrem1, SpriteKind.GoodProjectile, function (sprite, otherSprite) {
    CharacterArrow.destroy()
    Gremlin1Statusbar.value += -1
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile15`, function (sprite, location) {
    mySprite.setVelocity(0, -125)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile13`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`myTile6`)
    JumpStatus = 2
    mySprite.setImage(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 8 8 8 8 2 f d 4 . . 
        . . 4 4 f 8 8 9 9 8 8 f 4 4 . . 
        . . . . . 8 9 8 8 9 8 . . . . . 
        . . . . . 8 8 . . 8 8 . . . . . 
        `)
})
function Character () {
    mySprite = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
    scene.cameraFollowSprite(mySprite)
    tiles.placeOnTile(mySprite, tiles.getTileLocation(row, column))
    mySprite.ay = 195
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (SwordUnlocked) {
        SwordInAction = true
        animation.runImageAnimation(
        mySprite,
        [img`
            ........................
            .....ffff...............
            ...fff22fff.............
            ..fff2222fff............
            .fffeeeeeefff...........
            .ffe222222eef...........
            .fe2ffffff2ef...........
            .ffffeeeeffff...........
            ffefbf44fbfeff..........
            fee41fddf14eef..........
            .ffffdddddeef...........
            fddddf444eef............
            fbbbbf2222f4e...........
            fbbbbf2222fd4...........
            .fccf45544f44...........
            ..ffffffff..............
            ....ff..ff..............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff..........
            .ffefbf44fbfeff.........
            .fee41fddf14eef.........
            fdfeeddddd4eff..........
            fbffee444edd4e..........
            fbf4f2222edde...........
            fcf.f22cccee............
            .ff.f44cdc4f............
            ....fffddcff............
            .....fddcff.............
            ....cddc................
            ....cdc.................
            ....cc..................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            .......ff...............
            .....ff22ff.............
            ...fff2222fff...........
            ..fff222222fff..........
            ..fff222222fff..........
            ..feeeeeeeeeeff.........
            .ffe22222222eff.........
            .fffffeeeefffff.........
            fdfefbf44fbfeff.........
            fbfe41fddf14ef..........
            fbffe4dddd4efe..........
            fcfef22222f4e...........
            .ff4f44554f4e...........
            ....ffffffdde...........
            .....ffffedde...........
            ..........ee............
            .........ccc............
            ........cc1cc...........
            .........c1c............
            .........c1c............
            .........c1c............
            .........c1c............
            `,img`
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff......ccc.
            .ffefbf44fbfeff....cddc.
            .ffefbf44fbfeff...cddc..
            .fee4dddddd4eef.ccddc...
            fdfeeddddd4eeffecddc....
            fbffee4444ee4fddccc.....
            fbf4f222222f1edde.......
            fcf.f222222f44ee........
            .ff.f445544f............
            ....ffffffff............
            .....ff..ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        50,
        false
        )
        timer.after(500, function () {
            SwordInAction = false
            mySprite.setImage(img`
                ......ffff..............
                ....fff22fff............
                ...fff2222fff...........
                ..fffeeeeeefff..........
                ..ffe222222eef..........
                ..fe2ffffff2ef..........
                ..ffffeeeeffff......ccc.
                .ffefbf44fbfeff....cddc.
                .ffefbf44fbfeff...cddc..
                .fee4dddddd4eef.ccddc...
                fdfeeddddd4eeffecddc....
                fbffee4444ee4fddccc.....
                fbf4f222222f1edde.......
                fcf.f888888f44ee........
                .ff.88999988............
                ....89988998............
                .....88..88.............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        })
    }
    if (BowUnlocked && ShootingUp) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . f f f f . . . e e . 
            . . . . f f e e e e f f e d d e 
            . . . f e e e f f e f e d d d e 
            . . f f f f f 2 2 f f d d d e . 
            . . f f e 2 e 2 2 e d d d e . . 
            . . f e 2 f 2 f f d d d e f . . 
            . . f f f 2 2 e d d d f f f . . 
            . f f e f 2 f d d d e f e f f . 
            . f e e f f d d d e f e e e f . 
            . . f e e d d d e e e e e f . . 
            . . . f d d d e e e e e f . . . 
            . . e d d d f f f f f f 4 e . . 
            . e d d d 2 2 2 2 2 2 f d 4 . . 
            e d d d f 8 8 8 8 8 8 f 4 4 . . 
            e d d e . 8 8 8 8 8 8 . . . . . 
            . e e . . 8 8 . . 8 8 . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . d d d d d d d d . . . . 
            . d d d d d f f f f d d d d d . 
            d d d . f f e e e e f f . d d d 
            . 1 . f e e e f f e e e f . 1 . 
            . . f f f f f 2 2 f f f f f . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f 2 f 2 e f . . 
            . . f f f 2 2 e e 2 2 f f f . . 
            . f f e f 2 f e e f 2 f e f f . 
            . f e e f f e e e e f e e e f . 
            . . f e e e e e e e e e e f . . 
            . . . f e e e e e e e e f . . . 
            . . . . f f f f f f f f . . . . 
            . . . . f 2 2 2 2 2 2 f . . . . 
            . . . . f 8 8 8 8 8 8 f . . . . 
            . . . . . 8 8 8 8 8 8 . . . . . 
            . . . . . 8 8 . . 8 8 . . . . . 
            `,img`
            . . . . . . f f f f . . . e e . 
            . . . . f f e e e e f f e d d e 
            . . . f e e e f f e f e d d d e 
            . . f f f f f 2 2 f f d d d e . 
            . . f f e 2 e 2 2 e d d d e . . 
            . . f e 2 f 2 f f d d d e f . . 
            . . f f f 2 2 e d d d f f f . . 
            . f f e f 2 f d d d e f e f f . 
            . f e e f f d d d e f e e e f . 
            . . f e e d d d e e e e e f . . 
            . . . f d d d e e e e e f . . . 
            . . e d d d f f f f f f 4 e . . 
            . e d d d 2 2 2 2 2 2 f d 4 . . 
            e d d d f 4 4 4 4 4 4 f 4 4 . . 
            e d d e . f f f f f f . . . . . 
            . e e . . f f . . f f . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        200,
        false
        )
        timer.after(200, function () {
            CharacterArrow = sprites.createProjectileFromSprite(img`
                . . 1 . . 
                . 1 1 1 . 
                . . d . . 
                . . d . . 
                . . d . . 
                . . d . . 
                . . d . . 
                . . d . . 
                . f f f . 
                . f . f . 
                `, mySprite, 0, -70)
            CharacterArrow.setKind(SpriteKind.GoodProjectile)
        })
        timer.after(500, function () {
            mySprite.setImage(img`
                . . . . . . f f f f . . e e . . 
                . . . . f f e e e e f e d d e . 
                . . . f e e e f f e e d d d e . 
                . . f f f f f 2 2 e d d d e . . 
                . . f f e 2 e 2 e d d d e f . . 
                . . f e 2 f 2 e d d d e e f . . 
                . . f f f 2 e d d d e f f f . . 
                . f f e f e d d d e 2 f e f f . 
                . f e e e d d d e e f e e e f . 
                . . f e d d d e e e e e e f . . 
                . . e d d d e e e e e e f . . . 
                . e d d d e f f f f f f 4 e . . 
                e d d d e 2 2 2 2 2 2 f d 4 . . 
                e d d e f 8 8 8 8 8 8 f 4 4 . . 
                . e e . . 8 8 8 8 8 8 . . . . . 
                . . . . . 8 8 . . 8 8 . . . . . 
                `)
        })
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile12`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`myTile6`)
    mySprite.setImage(img`
        ....ffffffff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff......ccc.
        .ffefbf44fbfeff....cddc.
        .ffefbf44fbfeff...cddc..
        .fee4dddddd4eef.ccddc...
        fdfeeddddd4eeffecddc....
        fbffee4444ee4fddccc.....
        fbf4f222222f1edde.......
        fcf.f888888f44ee........
        .ff.88999988............
        ....89988998............
        ....888..888............
        `)
    SwordUnlocked = true
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Chest, function (sprite, otherSprite) {
    LegendaryChest.destroy()
    mySprite.setImage(img`
        ...............eee..
        .........ffff.edde..
        .......fff22fffdde..
        ......fff2222fffe...
        .....fffeeeeeefff...
        .....ffe222222eef...
        .....fe2ffffff2ef...
        .....ffffeeeeffff...
        ....ffefbf44fbfeff..
        ...efee41fddf14eef..
        ..eddfeeddddddeef...
        ..eddefee4444eef....
        ..eee.4f222222f4e...
        .....4df222222fd4...
        .....44f445544f44...
        ........ffffff......
        ........ff..ff......
        ....................
        ....................
        `)
    game.showLongText("This bow should serve as a replace to your damaged sword!", DialogLayout.Bottom)
    timer.after(500, function () {
        Gremlin41 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fee1111eef.......
            ......feeee11eeeef......
            ......fd1ee11ee1df......
            ......fdd2221222df......
            ......fbd21fdf12bf......
            ......fcd2ff1ff2cf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.SuperGrem1)
        tiles.placeOnTile(Gremlin41, tiles.getTileLocation(38, 46))
        Gremlin1Statusbar = statusbars.create(20, 4, StatusBarKind.Health)
        Gremlin1Statusbar.attachToSprite(Gremlin41)
        Gremlin1Statusbar.value = 100
        Gremlin42 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fee1111eef.......
            ......feeee11eeeef......
            ......fd1ee11ee1df......
            ......fdd2221222df......
            ......fbd21fdf12bf......
            ......fcd2ff1ff2cf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.SuperGrem2)
        tiles.placeOnTile(Gremlin42, tiles.getTileLocation(40, 46))
        Gremlin2Statusbar = statusbars.create(20, 4, StatusBarKind.Health)
        Gremlin2Statusbar.attachToSprite(Gremlin42)
        Gremlin2Statusbar.value = 100
        SuperGremlinsAlive = true
        ShootingUp = true
        SwordUnlocked = false
        BowUnlocked = true
        key = 1
        game.showLongText("What has just appeared...", DialogLayout.Bottom)
    })
    timer.after(200, function () {
        mySprite.setImage(img`
            . . . . . . f f f f . . e e . . 
            . . . . f f e e e e f e d d e . 
            . . . f e e e f f e e d d d e . 
            . . f f f f f 2 2 e d d d e . . 
            . . f f e 2 e 2 e d d d e f . . 
            . . f e 2 f 2 e d d d e e f . . 
            . . f f f 2 e d d d e f f f . . 
            . f f e f e d d d e 2 f e f f . 
            . f e e e d d d e e f e e e f . 
            . . f e d d d e e e e e e f . . 
            . . e d d d e e e e e e f . . . 
            . e d d d e f f f f f f 4 e . . 
            e d d d e 2 2 2 2 2 2 f d 4 . . 
            e d d e f 8 8 8 8 8 8 f 4 4 . . 
            . e e . . 8 8 8 8 8 8 . . . . . 
            . . . . . 8 8 . . 8 8 . . . . . 
            `)
    })
})
sprites.onOverlap(SpriteKind.SuperGrem2, SpriteKind.GoodProjectile, function (sprite, otherSprite) {
    CharacterArrow.destroy()
    Gremlin2Statusbar.value += -1
})
function Level1 () {
    tiles.setTilemap(tilemap`level1`)
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile16`, function (sprite, location) {
    if (key == 1) {
        tiles.setTileAt(tiles.getTileLocation(9, 42), assets.tile`myTile7`)
        tiles.setWallAt(tiles.getTileLocation(8, 42), false)
        tiles.setWallAt(tiles.getTileLocation(8, 41), false)
        tiles.setWallAt(tiles.getTileLocation(8, 40), false)
        tiles.setTileAt(tiles.getTileLocation(9, 41), sprites.dungeon.floorDark0)
        tiles.setTileAt(tiles.getTileLocation(9, 40), assets.tile`myTile8`)
        scene.cameraShake(4, 500)
    }
})
function SheildGremlins () {
    Gremlin11 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin11, tiles.getTileLocation(37, 35))
    Gremlin11.setBounceOnWall(true)
    Gremlin11.vx = 15
    Gremlin12 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin12, tiles.getTileLocation(42, 35))
    Gremlin12.setBounceOnWall(true)
    Gremlin12.vx = 15
    Gremlin21 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin21, tiles.getTileLocation(36, 39))
    Gremlin21.setBounceOnWall(true)
    Gremlin21.vx = 15
    Gremlin22 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin22, tiles.getTileLocation(41, 39))
    Gremlin22.setBounceOnWall(true)
    Gremlin22.vx = 15
    Gremlin31 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin31, tiles.getTileLocation(36, 43))
    Gremlin31.setBounceOnWall(true)
    Gremlin31.vx = 15
    Gremlin32 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin32, tiles.getTileLocation(40, 43))
    Gremlin32.setBounceOnWall(true)
    Gremlin32.vx = 15
}
controller.B.onEvent(ControllerButtonEvent.Released, function () {
    Shield.destroy()
    SheildCreated = false
})
function EvilDragon () {
    Boss = sprites.create(img`
        ............ccc.........
        .......cccccccc.........
        .....cc55555cc..cc......
        ....c555555555cccc......
        ...c55555555555bcc......
        ..c555551ff55555b..cc...
        ..c55d55ff5555555bccc...
        ..c55555555d55555bcc....
        ..c5555d5555d55555b.....
        ..cbbbb55555ddd555b.cc..
        ..c555d5555ddddd55dccc..
        ...c555dbbbdddbd5ddcc...
        ....cccbbbbb555bdddb....
        ....cbbbbbbc555bdddccc..
        ...cbbbbbbc555bddddcc...
        ...cbbbbbc555bdddddc....
        ..ccbbbbbc55bddddddcc...
        ..ccbbbbbbcb55dddddbcc..
        ...cbbbbbb5555ddddddddcc
        ....cbbbbb555ddbdddddddc
        ....cccbbc55ddbbbddddcc.
        ...ccdddccddddbcbbccc...
        ...ccccccd555ddccc......
        ........cccccccc........
        `, SpriteKind.Boss)
    tiles.placeOnTile(Boss, tiles.getTileLocation(14, 12))
    BossinitilizeFire = true
}
function CharacterTestCheat () {
    mySprite.ay = 0
    mySprite.vy = 0
    controller.moveSprite(mySprite, 200, 200)
}
scene.onOverlapTile(SpriteKind.Player, sprites.castle.tileGrass1, function (sprite, location) {
    mySprite.ay = 0
    mySprite.vy = 0
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile35`, function (sprite, location) {
    tiles.placeOnTile(mySprite, tiles.getTileLocation(11, 13))
    moveOnY = 100
    EvilDragon()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (SwordInAction) {
        otherSprite.destroy(effects.ashes, 200)
        GremlinKillCount += 1
    }
})
let GremlinShoota2: Sprite = null
let GremlinShoota1: Sprite = null
let FireBall: Sprite = null
let Boss: Sprite = null
let Gremlin32: Sprite = null
let Gremlin31: Sprite = null
let Gremlin22: Sprite = null
let Gremlin21: Sprite = null
let Gremlin12: Sprite = null
let Gremlin11: Sprite = null
let Gremlin2Statusbar: StatusBarSprite = null
let Gremlin42: Sprite = null
let Gremlin41: Sprite = null
let ShootingUp = false
let SwordInAction = false
let Gremlin1Statusbar: StatusBarSprite = null
let CharacterArrow: Sprite = null
let SheildCreated = false
let Shield: Sprite = null
let TheWiseOne: Sprite = null
let mySprite: Sprite = null
let LegendaryChest: Sprite = null
let SuperGremlinsAlive = false
let SwordUnlocked = false
let BossinitilizeFire = false
let JumpStatus = 0
let JumpCount = 0
let moveOnY = 0
let BowUnlocked = false
let key = 0
let row = 0
let column = 0
column = 47
row = 11
key = 0
Level1()
Character()
SheildGremlins()
WiseOne()
BowUnlocked = false
let AssistantAlive = false
let GremlinKillCount = 0
let moveOnX = 100
moveOnY = 0
let moveWithButtonsAllowed = 1
JumpCount = 0
JumpStatus = 1
BossinitilizeFire = false
SwordUnlocked = false
let GremlinX = 41
SuperGremlinsAlive = false
let GremlinY = 48
timer.after(500, function () {
    tiles.setTileAt(tiles.getTileLocation(13, 46), assets.tile`myTile8`)
    tiles.setTileAt(tiles.getTileLocation(13, 47), assets.tile`myTile7`)
    scene.cameraShake(4, 500)
})
LegendaryChest = sprites.create(assets.tile`myTile42`, SpriteKind.Chest)
tiles.placeOnTile(LegendaryChest, tiles.getTileLocation(36, 49))
CharacterTestCheat()
game.onUpdateInterval(5000, function () {
    if (BossinitilizeFire) {
        animation.runImageAnimation(
        Boss,
        [img`
            ........................
            ........................
            ..........ccc...........
            .........cccc...........
            .....ccccccc..ccc.......
            ...cc555555cccccc.......
            ..c5555555555bcc........
            .c555555555555b..cc.....
            c555551ff555555bccc.....
            c55d55ff55555555bc......
            c5555555555555555b......
            .cbb31bb5555dd555b.cc...
            .c5333b555ddddd55dccc...
            .c533b55ddddddddddb.....
            .c5555dddbb55bdddddccc..
            ..ccccbbbb555bdddddccc..
            ...cdcbc5555bddddddcc...
            ....ccbc55bc5ddddddbcccc
            .....cbbcc5555dddddddddc
            .....ccbbb555ddbddddddc.
            .....cdcbc55ddbbbdddcc..
            ...ccdddccddddbcbbcc....
            ...ccccccd555ddccc......
            ........cccccccc........
            `,img`
            ............ccc.........
            .......cccccccc.........
            .....cc55555cc..cc......
            ....c555555555cccc......
            ...c55555555555bcc......
            ..c555551ff55555b..cc...
            ..c55d55ff5555555bccc...
            ..c55555555d55555bcc....
            ..c5555d5555d55555b.....
            ..cbbbb55555ddd555b.cc..
            ..c555d5555ddddd55dccc..
            ...c555dbbbdddbd5ddcc...
            ....cccbbbbb555bdddb....
            ....cbbbbbbc555bdddccc..
            ...cbbbbbbc555bddddcc...
            ...cbbbbbc555bdddddc....
            ..ccbbbbbc55bddddddcc...
            ..ccbbbbbbcb55dddddbcc..
            ...cbbbbbb5555ddddddddcc
            ....cbbbbb555ddbdddddddc
            ....cccbbc55ddbbbddddcc.
            ...ccdddccddddbcbbccc...
            ...ccccccd555ddccc......
            ........cccccccc........
            `,img`
            .............ccc........
            ........cccccccc........
            ......cc55555cc..cc.....
            .....c555555555cccc.....
            ....c55555555555bcc.....
            ...c555555ccb5555b.cc...
            ...c55d55c55555555bcc...
            ...c55555555dd5555bc....
            ...c5555d5555dd5555.....
            ...cbbbd555555dd555.cc..
            ...c555d555555ddd55ccc..
            ....c555d5555ddbd5dcc...
            ....cccbbbbb555bdddb....
            ...cbbbbbbbc555bdddccc..
            ..cbbbbbbbc555bddddcc...
            ..cbbbbbbc555bdddddc....
            .ccbbbbbbc55bddddddcc...
            .ccbbbbbbbcb55dddddbc...
            ..cbbbbbbb5555ddddddbc..
            ...cbbbbbb555ddbddddddc.
            ....cccbbc55ddbbbddddddc
            ...ccdddccddddbcbbcccccc
            ...ccccccd555ddccc......
            ........cccccccc........
            `,img`
            ........................
            ........................
            ........................
            ..........ccc...........
            .........cccc...........
            .....ccccccc..ccc.......
            ...cc555555cccccc.......
            ..c5555555555bcc........
            .c555555555555b..cc.....
            c555555ccb55555bccc.....
            c55d55c555555555bc......
            c5555555555555555b......
            .cbbb1bb5555dd555b.cc...
            .c533bbbb5ddddd55dcc....
            .c533bbbb5ddddddddbcc...
            .c533bbb55dddddddddcccc.
            .c5333bb5bb55bdddddcccdc
            .c5333b5bb555bddddddbddc
            .c53335b5555bddddddddddc
            ..c5555c55bb55dbddddddcc
            ...cccbccc55ddbbbddddcc.
            ....cdddccddddbcbbbcc...
            ....cccccd555ddcccc.....
            ........cccccccc........
            `,img`
            ........................
            ........................
            ........................
            ..........ccc...........
            .........cccc...........
            .....ccccccc..ccc.......
            ...cc555555cccccc.......
            ..c5555555555bcc........
            .c555555555555b..cc.....
            c555555ccb55555bccc.....
            c55d55c555555555bc......
            c5555555555555555b......
            .cbbb1bb5555dd555b.cc...
            .c533bbbb5ddddd55dcc....
            .c533bbbb5ddddddddbcc...
            .c5333bb55dddddddddcccc.
            .c5333b55bb55bdddddcccdc
            .c533355bb555bddddddbddc
            ..c5555b5555bddddddddddc
            ...cccbc55bb55dbddddddcc
            .....cbbcc55ddbbbddddcc.
            ....cdddccddddbcbbbcc...
            ....cccccd555ddcccc.....
            ........cccccccc........
            `,img`
            ........................
            ........................
            ........................
            ..........ccc...........
            .........cccc...........
            .....ccccccc..ccc.......
            ...cc555555cccccc.......
            ..c5555555555bcc........
            .c555555555555b..cc.....
            c555555ccb55555bccc.....
            c55d55c555555555bc......
            c5555555555555555b......
            .cbbb1bb5555dd555b.cc...
            .c533bbb55ddddd55dcc....
            .c5333bb5dddddddddbcc...
            .c5333b55ddddddddddcccc.
            .c533355dbb55bdddddcccdc
            ..c55555bb555bddddddbddc
            ...cccbb5555bddddddddddc
            .....cbc55bb55dbddddddcc
            .....cdbcc55ddbbbddddcc.
            ....cdddccddddbcbbbcc...
            ....cccccd555ddcccc.....
            ........cccccccc........
            `],
        500,
        false
        )
        FireBall = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 4 4 4 4 4 . . . . . . 
            . . . 4 4 4 5 5 5 d 4 4 4 4 . . 
            . . 4 d 5 d 5 5 5 d d d 4 4 . . 
            . . 4 5 5 1 1 1 d d 5 5 5 4 . . 
            . 4 5 5 5 1 1 1 5 1 1 5 5 4 4 . 
            . 4 d d 1 1 5 5 5 1 1 5 5 d 4 . 
            . 4 5 5 1 1 5 1 1 5 5 d d d 4 . 
            . 4 5 5 5 d 1 1 1 5 1 1 5 5 2 . 
            . 4 d 5 5 d 1 1 1 5 1 1 5 5 2 . 
            . . 4 4 d d 5 5 5 5 d d 5 4 . . 
            . . 4 4 2 4 d 5 5 d d 4 4 4 . . 
            . . . 4 4 2 2 4 4 4 2 4 4 . . . 
            . . . . . 4 4 4 4 4 4 . . . . . 
            . . . . . . . . . . . . . . . . 
            `, Boss, 1, 1)
        FireBall.setKind(SpriteKind.Projectile)
        FireBall.follow(mySprite, 30)
    }
})
forever(function () {
    if (GremlinKillCount == 2) {
        tiles.setWallAt(tiles.getTileLocation(36, 36), false)
        tiles.setWallAt(tiles.getTileLocation(37, 36), false)
        tiles.setWallAt(tiles.getTileLocation(38, 36), false)
        tiles.setWallAt(tiles.getTileLocation(39, 36), false)
        tiles.setWallAt(tiles.getTileLocation(40, 36), false)
        tiles.setWallAt(tiles.getTileLocation(41, 36), false)
        tiles.setWallAt(tiles.getTileLocation(42, 36), false)
        tiles.setTileAt(tiles.getTileLocation(35, 36), sprites.dungeon.darkGroundWest)
        tiles.setTileAt(tiles.getTileLocation(36, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(37, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(38, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(39, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(40, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(41, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(42, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(43, 36), sprites.dungeon.darkGroundEast)
    }
    if (GremlinKillCount == 4) {
        tiles.setWallAt(tiles.getTileLocation(36, 40), false)
        tiles.setWallAt(tiles.getTileLocation(37, 40), false)
        tiles.setWallAt(tiles.getTileLocation(38, 40), false)
        tiles.setWallAt(tiles.getTileLocation(39, 40), false)
        tiles.setWallAt(tiles.getTileLocation(40, 40), false)
        tiles.setWallAt(tiles.getTileLocation(41, 40), false)
        tiles.setWallAt(tiles.getTileLocation(42, 40), false)
        tiles.setTileAt(tiles.getTileLocation(35, 40), sprites.dungeon.darkGroundWest)
        tiles.setTileAt(tiles.getTileLocation(36, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(37, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(38, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(39, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(40, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(41, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(42, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(43, 40), sprites.dungeon.darkGroundEast)
    }
    if (GremlinKillCount == 6) {
        mySprite.setImage(img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 8 8 8 8 2 f d 4 . . 
            . . 4 4 f 8 8 9 9 8 8 f 4 4 . . 
            . . . . . 8 9 8 8 9 8 . . . . . 
            . . . . . 8 8 . . 8 8 . . . . . 
            `)
        timer.after(500, function () {
            game.showLongText("Oh no! Your sword has broken", DialogLayout.Bottom)
            tiles.setWallAt(tiles.getTileLocation(36, 44), false)
            tiles.setWallAt(tiles.getTileLocation(37, 44), false)
            tiles.setWallAt(tiles.getTileLocation(38, 44), false)
            tiles.setWallAt(tiles.getTileLocation(39, 44), false)
            tiles.setWallAt(tiles.getTileLocation(40, 44), false)
            tiles.setWallAt(tiles.getTileLocation(41, 44), false)
            tiles.setWallAt(tiles.getTileLocation(42, 44), false)
            tiles.setTileAt(tiles.getTileLocation(35, 44), sprites.dungeon.darkGroundWest)
            tiles.setTileAt(tiles.getTileLocation(36, 44), sprites.dungeon.darkGroundCenter)
            tiles.setTileAt(tiles.getTileLocation(37, 44), sprites.dungeon.darkGroundCenter)
            tiles.setTileAt(tiles.getTileLocation(38, 44), sprites.dungeon.darkGroundCenter)
            tiles.setTileAt(tiles.getTileLocation(39, 44), sprites.dungeon.darkGroundCenter)
            tiles.setTileAt(tiles.getTileLocation(40, 44), sprites.dungeon.darkGroundCenter)
            tiles.setTileAt(tiles.getTileLocation(41, 44), sprites.dungeon.darkGroundCenter)
            tiles.setTileAt(tiles.getTileLocation(42, 44), sprites.dungeon.darkGroundCenter)
            tiles.setTileAt(tiles.getTileLocation(43, 44), sprites.dungeon.darkGroundEast)
        })
        GremlinKillCount = 7
    }
})
forever(function () {
    if (SheildCreated) {
        Shield.setPosition(mySprite.x + 13, mySprite.y)
    }
})
forever(function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        JumpCount = 0
    }
})
game.onUpdateInterval(randint(4000, 7500), function () {
    if (SuperGremlinsAlive) {
        animation.runImageAnimation(
        Gremlin41,
        [img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ffe11eff........
            .......feee1eeebf.......
            .....fffcee1ee11f.......
            ...fc111222112221f......
            ...f1b1b21f11f12df......
            ...fbfbf2ff11ff2df......
            ......fcf111111bbf......
            .......ccbdb1b1fcf......
            .......fffbfbfdff.......
            ........ffffffff........
            ........fffffffffff.....
            .........fffffc111cf....
            .........fffff1b1b1f....
            ..........ffffbfbfbf....
            ...........ffff.........
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ....7.fdee1111eedf......
            ...7..feeee11eeeef......
            ...7..fd1ee11ee1df......
            ...7..fd22211222dff.....
            ...77.fb2f1ddf12bfcf....
            ...777fc2ff11ff2cfbf....
            ....77fffbdb1bdffcf.....
            ....fcb1bcffffff........
            ....f1c1c1ffffff........
            ....fdfdfdfffff.........
            .....f.f.f..............
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fee1111eef.......
            ......feeee11eeeef......
            ......fd1ee11ee1df......
            ......fd22211222df......
            ......fc21f11f12cff.....
            .......f2ff11ff2fbbf....
            .......ffbdb1bdffff.....
            ........fcbfbfdf........
            ........ffffffff........
            ......ffffffffff........
            .....fcb1bcffff.........
            ......ffbff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fee1111eef.......
            ......feeee11eeeef......
            ......fddee11eeddf......
            ......fb22211222df......
            ......fc21fddf12bf......
            .......f2ff11ff2fff.....
            .......ffb1111bcfbcf....
            ........fcdb1bdfbbbf....
            .......ffffffffffcf.....
            .....fcb1bcfffff........
            .....f1b1b1ffff.........
            ......ffbff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        500,
        false
        )
        GremlinShoota1 = sprites.createProjectileFromSprite(img`
            . . c c c c b b c . . 
            . c c b b b b b c c . 
            c c c b c c c c c c c 
            c b b b b b c c c c c 
            c b b c c c c c b c c 
            c c c c b b b c b c c 
            c c b b c c b b b c c 
            c c b b b b b c b c c 
            c c b b c c b b c c c 
            . c c c b b b b b c . 
            . . c c c c c c c . . 
            `, Gremlin41, 20, 20)
    }
})
game.onUpdateInterval(randint(4000, 7500), function () {
    if (SuperGremlinsAlive) {
        animation.runImageAnimation(
        Gremlin42,
        [img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ffe11eff........
            .......feee1eeebf.......
            .....fffcee1ee11f.......
            ...fc111222112221f......
            ...f1b1b21f11f12df......
            ...fbfbf2ff11ff2df......
            ......fcf111111bbf......
            .......ccbdb1b1fcf......
            .......fffbfbfdff.......
            ........ffffffff........
            ........fffffffffff.....
            .........fffffc111cf....
            .........fffff1b1b1f....
            ..........ffffbfbfbf....
            ...........ffff.........
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ....7.fdee1111eedf......
            ...7..feeee11eeeef......
            ...7..fd1ee11ee1df......
            ...7..fd22211222dff.....
            ...77.fb2f1ddf12bfcf....
            ...777fc2ff11ff2cfbf....
            ....77fffbdb1bdffcf.....
            ....fcb1bcffffff........
            ....f1c1c1ffffff........
            ....fdfdfdfffff.........
            .....f.f.f..............
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fee1111eef.......
            ......feeee11eeeef......
            ......fd1ee11ee1df......
            ......fd22211222df......
            ......fc21f11f12cff.....
            .......f2ff11ff2fbbf....
            .......ffbdb1bdffff.....
            ........fcbfbfdf........
            ........ffffffff........
            ......ffffffffff........
            .....fcb1bcffff.........
            ......ffbff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fee1111eef.......
            ......feeee11eeeef......
            ......fddee11eeddf......
            ......fb22211222df......
            ......fc21fddf12bf......
            .......f2ff11ff2fff.....
            .......ffb1111bcfbcf....
            ........fcdb1bdfbbbf....
            .......ffffffffffcf.....
            .....fcb1bcfffff........
            .....f1b1b1ffff.........
            ......ffbff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        500,
        false
        )
        GremlinShoota2 = sprites.createProjectileFromSprite(img`
            . . c c c c b b c . . 
            . c c b b b b b c c . 
            c c c b c c c c c c c 
            c b b b b b c c c c c 
            c b b c c c c c b c c 
            c c c c b b b c b c c 
            c c b b c c b b b c c 
            c c b b b b b c b c c 
            c c b b c c b b c c c 
            . c c c b b b b b c . 
            . . c c c c c c c . . 
            `, Gremlin42, 20, 30)
    }
})
