namespace SpriteKind {
    export const Protectoion = SpriteKind.create()
    export const Boss = SpriteKind.create()
    export const Chest = SpriteKind.create()
    export const GoodProjectile = SpriteKind.create()
    export const SuperGrem2 = SpriteKind.create()
    export const SuperGrem1 = SpriteKind.create()
    export const EnemeyProjectile = SpriteKind.create()
    export const Princes = SpriteKind.create()
    export const DifferentPlayer = SpriteKind.create()
}
namespace StatusBarKind {
    export const SheildCooldown = StatusBarKind.create()
    export const Gremlin1Status = StatusBarKind.create()
    export const Gremlin2Status = StatusBarKind.create()
}
scene.onOverlapTile(SpriteKind.GoodProjectile, sprites.dungeon.floorLight0, function (sprite, location) {
    sprite.destroy()
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (JumpCount < JumpStatus) {
        mySprite.vy = -140
        JumpCount += 1
    }
})
function WiseOne () {
    TheWiseOne = sprites.create(img`
        . . . . . . . c c . . . . . . . 
        . . . . . . c 5 c . . . . . . . 
        . . . . c c 5 5 5 c c c . . . . 
        . . c c c c 5 5 5 5 c b c c . . 
        . c b b 5 b 5 5 5 5 b 5 b b c . 
        . c b 5 5 b b 5 5 b b 5 5 b c . 
        . . c 5 5 5 b b b b 5 5 5 f . . 
        . . . f 5 5 5 5 5 5 5 5 f f . . 
        . . . . f e e e f b e e f f . . 
        . . . . f e b b f 1 b f f f . . 
        . . . . f b b b b b b f f . . . 
        . . . . . f e e e e f e e . . . 
        . . . . . f 5 b b e b b e . . . 
        . . . . f 5 5 5 5 e b b e . . . 
        . . . . c b 5 5 5 5 e e . . . . 
        . . . . . f f f f f f . . . . . 
        `, SpriteKind.Player)
    tiles.placeOnTile(TheWiseOne, tiles.getTileLocation(31, 28))
}
statusbars.onStatusReached(StatusBarKind.Gremlin1Status, statusbars.StatusComparison.EQ, statusbars.ComparisonType.Percentage, 40, function (status) {
    Gremlin41.vx = SuperGremlinVelo * 5
    SuperGremlinInvincible = true
    timer.after(5000, function () {
        SuperGremlinInvincible = false
        GremlinShootSpeed = 2500
        Gremlin41.vx = 20
    })
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.SuperGrem1, function (sprite, otherSprite) {
    if (SwordInAction) {
        CharacterStatusBar.value += -10
    }
    timer.after(300, function () {
        if (SwordInAction == false) {
            CharacterStatusBar.value += -5
            BLAHAHHSJFFKDF = true
            animation.runImageAnimation(
            otherSprite,
            [img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .....fffc1111111f.......
                ...fc111cd1111111f......
                ...f1b1b1b1111dddf......
                ...fbfbffcf11fcddf......
                ......fcf111111bbf......
                .......ccbdb1b1fcf......
                .......fffbfbfdff.......
                ........ffffffff........
                ........fffffffffff.....
                .........fffffc111cf....
                .........fffff1b1b1f....
                ..........ffffbfbfbf....
                ...........ffff.........
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ....7.fd11111111df......
                ...7..fd11111111df......
                ...7..fd11111111df......
                ...7..fddd1111dddff.....
                ...77.fbdbfddfbdbfcf....
                ...777fcdcf11fcdcfbf....
                ....77fffbdb1bdffcf.....
                ....fcb1bcffffff........
                ....f1c1c1ffffff........
                ....fdfdfdfffff.........
                .....f.f.f..............
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd111111111f......
                ......fd11111111df......
                ......fd11111111df......
                ......fcdd1111ddcff.....
                .......fbcf11fcbfbbf....
                .......ffbdb1bdffff.....
                ........fcbfbfdf........
                ........ffffffff........
                ......ffffffffff........
                .....fcb1bcffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ......fdd111111ddf......
                ......fbdd1111dddf......
                ......fcdbfddfbdbf......
                .......fbcf11fcbfff.....
                .......ffb1111bcfbcf....
                ........fcdb1bdfbbbf....
                .......ffffffffffcf.....
                .....fcb1bcfffff........
                .....f1b1b1ffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                `],
            500,
            false
            )
            timer.after(300, function () {
                BLAHAHHSJFFKDF = false
            })
        }
    })
    pause(500)
})
sprites.onOverlap(SpriteKind.SuperGrem1, SpriteKind.GoodProjectile, function (sprite, otherSprite) {
    if (SuperGremlinInvincible == false) {
        CharacterArrow.destroy()
        Gremlin1Statusbar.value += -10
    } else {
        CharacterArrow.destroy()
        Gremlin1Statusbar.value += 10
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile15`, function (sprite, location) {
    mySprite.setVelocity(0, -125)
    BowUnlocked = false
    timer.after(1000, function () {
        tiles.placeOnTile(mySprite, tiles.getTileLocation(30, 28))
    })
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile13`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`myTile6`)
    JumpStatus = 2
    mySprite.setImage(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 8 8 8 8 2 f d 4 . . 
        . . 4 4 f 8 8 9 9 8 8 f 4 4 . . 
        . . . . . 8 9 8 8 9 8 . . . . . 
        . . . . . 8 8 . . 8 8 . . . . . 
        `)
    game.showLongText("You can now double jump with these new boots.", DialogLayout.Bottom)
})
function Character () {
    mySprite = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
    scene.cameraFollowSprite(mySprite)
    tiles.placeOnTile(mySprite, tiles.getTileLocation(row, column))
    mySprite.ay = 195
    controller.moveSprite(mySprite, 100, 0)
    CharacterStatusBar = statusbars.create(12, 2, StatusBarKind.Health)
    CharacterStatusBar.attachToSprite(mySprite, 2, 0)
    CharacterStatusBar.value = 100
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (SwordUnlocked) {
        SwordInAction = true
        animation.runImageAnimation(
        mySprite,
        [img`
            ........................
            .....ffff...............
            ...fff22fff.............
            ..fff2222fff............
            .fffeeeeeefff...........
            .ffe222222eef...........
            .fe2ffffff2ef...........
            .ffffeeeeffff...........
            ffefbf44fbfeff..........
            fee41fddf14eef..........
            .ffffdddddeef...........
            fddddf444eef............
            fbbbbf2222f4e...........
            fbbbbf2222fd4...........
            .fccf45544f44...........
            ..ffffffff..............
            ....ff..ff..............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff..........
            .ffefbf44fbfeff.........
            .fee41fddf14eef.........
            fdfeeddddd4eff..........
            fbffee444edd4e..........
            fbf4f2222edde...........
            fcf.f22cccee............
            .ff.f44cdc4f............
            ....fffddcff............
            .....fddcff.............
            ....cddc................
            ....cdc.................
            ....cc..................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            .......ff...............
            .....ff22ff.............
            ...fff2222fff...........
            ..fff222222fff..........
            ..fff222222fff..........
            ..feeeeeeeeeeff.........
            .ffe22222222eff.........
            .fffffeeeefffff.........
            fdfefbf44fbfeff.........
            fbfe41fddf14ef..........
            fbffe4dddd4efe..........
            fcfef22222f4e...........
            .ff4f44554f4e...........
            ....ffffffdde...........
            .....ffffedde...........
            ..........ee............
            .........ccc............
            ........cc1cc...........
            .........c1c............
            .........c1c............
            .........c1c............
            .........c1c............
            `,img`
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff......ccc.
            .ffefbf44fbfeff....cddc.
            .ffefbf44fbfeff...cddc..
            .fee4dddddd4eef.ccddc...
            fdfeeddddd4eeffecddc....
            fbffee4444ee4fddccc.....
            fbf4f222222f1edde.......
            fcf.f222222f44ee........
            .ff.f445544f............
            ....ffffffff............
            .....ff..ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        50,
        false
        )
        timer.after(500, function () {
            SwordInAction = false
            mySprite.setImage(img`
                ......ffff..............
                ....fff22fff............
                ...fff2222fff...........
                ..fffeeeeeefff..........
                ..ffe222222eef..........
                ..fe2ffffff2ef..........
                ..ffffeeeeffff......ccc.
                .ffefbf44fbfeff....cddc.
                .ffefbf44fbfeff...cddc..
                .fee4dddddd4eef.ccddc...
                fdfeeddddd4eeffecddc....
                fbffee4444ee4fddccc.....
                fbf4f222222f1edde.......
                fcf.f888888f44ee........
                .ff.88999988............
                ....89988998............
                .....88..88.............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        })
    }
    if (BowUnlocked) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . f f f f . . . e e . 
            . . . . f f e e e e f f e d d e 
            . . . f e e e f f e f e d d d e 
            . . f f f f f 2 2 f f d d d e . 
            . . f f e 2 e 2 2 e d d d e . . 
            . . f e 2 f 2 f f d d d e f . . 
            . . f f f 2 2 e d d d f f f . . 
            . f f e f 2 f d d d e f e f f . 
            . f e e f f d d d e f e e e f . 
            . . f e e d d d e e e e e f . . 
            . . . f d d d e e e e e f . . . 
            . . e d d d f f f f f f 4 e . . 
            . e d d d 2 2 2 2 2 2 f d 4 . . 
            e d d d f 8 8 8 8 8 8 f 4 4 . . 
            e d d e . 8 8 8 8 8 8 . . . . . 
            . e e . . 8 8 . . 8 8 . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . d d d d d d d d . . . . 
            . d d d d d f f f f d d d d d . 
            d d d . f f e e e e f f . d d d 
            . 1 . f e e e f f e e e f . 1 . 
            . . f f f f f 2 2 f f f f f . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f 2 f 2 e f . . 
            . . f f f 2 2 e e 2 2 f f f . . 
            . f f e f 2 f e e f 2 f e f f . 
            . f e e f f e e e e f e e e f . 
            . . f e e e e e e e e e e f . . 
            . . . f e e e e e e e e f . . . 
            . . . . f f f f f f f f . . . . 
            . . . . f 2 2 2 2 2 2 f . . . . 
            . . . . f 8 8 8 8 8 8 f . . . . 
            . . . . . 8 8 8 8 8 8 . . . . . 
            . . . . . 8 8 . . 8 8 . . . . . 
            `,img`
            . . . . . . f f f f . . . e e . 
            . . . . f f e e e e f f e d d e 
            . . . f e e e f f e f e d d d e 
            . . f f f f f 2 2 f f d d d e . 
            . . f f e 2 e 2 2 e d d d e . . 
            . . f e 2 f 2 f f d d d e f . . 
            . . f f f 2 2 e d d d f f f . . 
            . f f e f 2 f d d d e f e f f . 
            . f e e f f d d d e f e e e f . 
            . . f e e d d d e e e e e f . . 
            . . . f d d d e e e e e f . . . 
            . . e d d d f f f f f f 4 e . . 
            . e d d d 2 2 2 2 2 2 f d 4 . . 
            e d d d f 4 4 4 4 4 4 f 4 4 . . 
            e d d e . f f f f f f . . . . . 
            . e e . . f f . . f f . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        200,
        false
        )
        timer.after(200, function () {
            CharacterArrow = sprites.createProjectileFromSprite(img`
                . . 1 . . 
                . 1 1 1 . 
                . . d . . 
                . . d . . 
                . . d . . 
                . . d . . 
                . . d . . 
                . . d . . 
                . f f f . 
                . f . f . 
                `, mySprite, 0, -70)
            CharacterArrow.setKind(SpriteKind.GoodProjectile)
        })
        timer.after(500, function () {
            mySprite.setImage(img`
                . . . . . . f f f f . . e e . . 
                . . . . f f e e e e f e d d e . 
                . . . f e e e f f e e d d d e . 
                . . f f f f f 2 2 e d d d e . . 
                . . f f e 2 e 2 e d d d e f . . 
                . . f e 2 f 2 e d d d e e f . . 
                . . f f f 2 e d d d e f f f . . 
                . f f e f e d d d e 2 f e f f . 
                . f e e e d d d e e f e e e f . 
                . . f e d d d e e e e e e f . . 
                . . e d d d e e e e e e f . . . 
                . e d d d e f f f f f f 4 e . . 
                e d d d e 2 2 2 2 2 2 f d 4 . . 
                e d d e f 8 8 8 8 8 8 f 4 4 . . 
                . e e . . 8 8 8 8 8 8 . . . . . 
                . . . . . 8 8 . . 8 8 . . . . . 
                `)
        })
        pause(750)
    } else {
    	
    }
})
statusbars.onZero(StatusBarKind.Gremlin1Status, function (status) {
    Gremlin41.destroy(effects.spray, 500)
    SuperGremlinsAlive = false
    tiles.setTileAt(tiles.getTileLocation(42, 49), assets.tile`myTile17`)
    mySprite.setImage(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 8 8 8 8 2 f d 4 . . 
        . . 4 4 f 8 8 9 9 8 8 f 4 4 . . 
        . . . . . 8 9 8 8 9 8 . . . . . 
        . . . . . 8 8 . . 8 8 . . . . . 
        `)
})
statusbars.onStatusReached(StatusBarKind.Health, statusbars.StatusComparison.LTE, statusbars.ComparisonType.Percentage, 50, function (status) {
    if (SuperGremlinsAlive) {
        game.showLongText("Above the gremlin is an apple to restore health, might take some part core and guts.", DialogLayout.Bottom)
    } else {
        AppleReminder = true
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile12`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`myTile6`)
    mySprite.setImage(img`
        ....ffffffff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff......ccc.
        .ffefbf44fbfeff....cddc.
        .ffefbf44fbfeff...cddc..
        .fee4dddddd4eef.ccddc...
        fdfeeddddd4eeffecddc....
        fbffee4444ee4fddccc.....
        fbf4f222222f1edde.......
        fcf.f888888f44ee........
        .ff.88999988............
        ....89988998............
        ....888..888............
        `)
    SwordUnlocked = true
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Chest, function (sprite, otherSprite) {
    LegendaryChest.destroy()
    mySprite.setImage(img`
        ...............eee..
        .........ffff.edde..
        .......fff22fffdde..
        ......fff2222fffe...
        .....fffeeeeeefff...
        .....ffe222222eef...
        .....fe2ffffff2ef...
        .....ffffeeeeffff...
        ....ffefbf44fbfeff..
        ...efee41fddf14eef..
        ..eddfeeddddddeef...
        ..eddefee4444eef....
        ..eee.4f222222f4e...
        .....4df222222fd4...
        .....44f445544f44...
        ........ffffff......
        ........ff..ff......
        ....................
        ....................
        `)
    game.showLongText("This bow should serve as a replace to your damaged sword!", DialogLayout.Bottom)
    timer.after(500, function () {
        Gremlin41 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fdeee11eeedf......
            ......fd11111111df......
            ......fdfff11fffdf......
            ......fbf1fddf1fbf......
            ......fcff1d1ff1cf......
            .......fb1d1111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.SuperGrem1)
        tiles.placeOnTile(Gremlin41, tiles.getTileLocation(39, 46))
        Gremlin1Statusbar = statusbars.create(20, 2, StatusBarKind.Gremlin1Status)
        Gremlin1Statusbar.value = 200
        Gremlin1Statusbar.attachToSprite(Gremlin41)
        tiles.setTileAt(tiles.getTileLocation(41, 42), sprites.dungeon.floorDark0)
        tiles.setWallAt(tiles.getTileLocation(41, 42), true)
        tiles.setTileAt(tiles.getTileLocation(36, 40), sprites.dungeon.floorDark0)
        tiles.setWallAt(tiles.getTileLocation(36, 40), true)
        tiles.setTileAt(tiles.getTileLocation(39, 36), sprites.dungeon.floorDark0)
        tiles.setWallAt(tiles.getTileLocation(39, 36), true)
        tiles.setTileAt(tiles.getTileLocation(42, 36), sprites.dungeon.floorDark0)
        tiles.setWallAt(tiles.getTileLocation(42, 35), true)
        tiles.setTileAt(tiles.getTileLocation(42, 34), assets.tile`myTile44`)
        Gremlin41.setBounceOnWall(true)
        SuperGremlinInvincible = false
        SuperGremlinsAlive = true
        GremlinOnSticks = false
        SwordUnlocked = false
        BowUnlocked = true
        key = 1
        game.showLongText("What has just appeared...", DialogLayout.Bottom)
        Gremlin41.vx = SuperGremlinVelo
        timer.after(200, function () {
            mySprite.setImage(img`
                . . . . . . f f f f . . e e . . 
                . . . . f f e e e e f e d d e . 
                . . . f e e e f f e e d d d e . 
                . . f f f f f 2 2 e d d d e . . 
                . . f f e 2 e 2 e d d d e f . . 
                . . f e 2 f 2 e d d d e e f . . 
                . . f f f 2 e d d d e f f f . . 
                . f f e f e d d d e 2 f e f f . 
                . f e e e d d d e e f e e e f . 
                . . f e d d d e e e e e e f . . 
                . . e d d d e e e e e e f . . . 
                . e d d d e f f f f f f 4 e . . 
                e d d d e 2 2 2 2 2 2 f d 4 . . 
                e d d e f 8 8 8 8 8 8 f 4 4 . . 
                . e e . . 8 8 8 8 8 8 . . . . . 
                . . . . . 8 8 . . 8 8 . . . . . 
                `)
            game.showLongText("Above the gremlin is an apple to restore health, might take some part core and guts.", DialogLayout.Bottom)
        })
    })
})
function Level1 () {
    tiles.setTilemap(tilemap`level1`)
}
statusbars.onStatusReached(StatusBarKind.Gremlin1Status, statusbars.StatusComparison.EQ, statusbars.ComparisonType.Percentage, 10, function (status) {
    Gremlin41.vx = SuperGremlinVelo * 5
    SuperGremlinInvincible = true
    timer.after(5000, function () {
        SuperGremlinInvincible = false
        GremlinShootSpeed = 2500
        Gremlin41.vx = 20
    })
})
scene.onOverlapTile(SpriteKind.EnemeyProjectile, sprites.dungeon.floorLight0, function (sprite, location) {
    if (SuperGremlinInvincible == false) {
        sprite.destroy()
    }
})
function princess () {
    Princess = sprites.create(img`
        . . . . . f f 4 4 f f . . . . . 
        . . . . f 5 4 5 5 4 5 f . . . . 
        . . . f e 4 5 5 5 5 4 e f . . . 
        . . f b 3 e 4 4 4 4 e 3 b f . . 
        . . f 3 3 3 3 3 3 3 3 3 3 f . . 
        . f 3 3 e b 3 e e 3 b e 3 3 f . 
        . f 3 3 f f e e e e f f 3 3 f . 
        . f b b f b f e e f b f b b f . 
        . f b b e 1 f 4 4 f 1 e b b f . 
        f f b b f 4 4 4 4 4 4 f b b f f 
        f b b f f f e e e e f f f b b f 
        . f e e f b d d d d b f e e f . 
        . . e 4 c d d d d d d c 4 e . . 
        . . e f b d b d b d b b f e . . 
        . . . f f 1 d 1 d 1 d f f . . . 
        . . . . . f f b b f f . . . . . 
        `, SpriteKind.Princes)
    tiles.placeOnTile(Princess, tiles.getTileLocation(6, 42))
}
statusbars.onZero(StatusBarKind.Health, function (status) {
    mySprite.destroy()
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile16`, function (sprite, location) {
    if (key == 1) {
        tiles.setTileAt(tiles.getTileLocation(9, 42), assets.tile`myTile7`)
        tiles.setWallAt(tiles.getTileLocation(8, 42), false)
        tiles.setWallAt(tiles.getTileLocation(8, 41), false)
        tiles.setWallAt(tiles.getTileLocation(8, 40), false)
        tiles.setTileAt(tiles.getTileLocation(9, 41), sprites.dungeon.floorDark0)
        tiles.setTileAt(tiles.getTileLocation(9, 40), assets.tile`myTile8`)
        scene.cameraShake(4, 500)
        PrincessTraped = false
        Princess.say("My hero!")
    }
    effects.confetti.startScreenEffect()
    timer.after(2000, function () {
        game.over(true)
    })
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile17`, function (sprite, location) {
    tiles.setWallAt(tiles.getTileLocation(43, 49), false)
    tiles.setWallAt(tiles.getTileLocation(43, 48), false)
    tiles.setTileAt(tiles.getTileLocation(42, 49), sprites.dungeon.darkGroundCenter)
    tiles.setTileAt(tiles.getTileLocation(43, 49), sprites.dungeon.darkGroundCenter)
    timer.after(100, function () {
        game.showLongText("Use this key to get out of this dungeon and get the princess!", DialogLayout.Bottom)
    })
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile44`, function (sprite, location) {
    tiles.setTileAt(tiles.getTileLocation(42, 34), assets.tile`myTile41`)
    CharacterStatusBar.value += 30
})
statusbars.onStatusReached(StatusBarKind.Gremlin1Status, statusbars.StatusComparison.EQ, statusbars.ComparisonType.Percentage, 70, function (status) {
    game.showLongText("Don't shoot him while he's mad! He will thrive on it!", DialogLayout.Bottom)
    Gremlin41.vx = SuperGremlinVelo * 5
    SuperGremlinInvincible = true
    timer.after(5000, function () {
        SuperGremlinInvincible = false
        GremlinShootSpeed = 2500
        Gremlin41.vx = 20
    })
})
function SheildGremlins () {
    Gremlin11 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin11, tiles.getTileLocation(37, 35))
    Gremlin11.setBounceOnWall(true)
    Gremlin11.vx = 15
    Gremlin12 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin12, tiles.getTileLocation(42, 35))
    Gremlin12.setBounceOnWall(true)
    Gremlin12.vx = 15
    Gremlin21 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin21, tiles.getTileLocation(36, 39))
    Gremlin21.setBounceOnWall(true)
    Gremlin21.vx = 15
    Gremlin22 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin22, tiles.getTileLocation(41, 39))
    Gremlin22.setBounceOnWall(true)
    Gremlin22.vx = 15
    Gremlin31 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin31, tiles.getTileLocation(36, 43))
    Gremlin31.setBounceOnWall(true)
    Gremlin31.vx = 15
    Gremlin32 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Gremlin32, tiles.getTileLocation(40, 43))
    Gremlin32.setBounceOnWall(true)
    Gremlin32.vx = 15
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Player, function (sprite, otherSprite) {
    TheWiseOne.setKind(SpriteKind.DifferentPlayer)
    game.showLongText("Be careful in the forbidden dungeon. Gremlins crawl in every corner. There is a sword in the chest to help.", DialogLayout.Bottom)
})
function EvilDragon () {
    Boss2 = sprites.create(img`
        ............ccc.........
        .......cccccccc.........
        .....cc55555cc..cc......
        ....c555555555cccc......
        ...c55555555555bcc......
        ..c555551ff55555b..cc...
        ..c55d55ff5555555bccc...
        ..c55555555d55555bcc....
        ..c5555d5555d55555b.....
        ..cbbbb55555ddd555b.cc..
        ..c555d5555ddddd55dccc..
        ...c555dbbbdddbd5ddcc...
        ....cccbbbbb555bdddb....
        ....cbbbbbbc555bdddccc..
        ...cbbbbbbc555bddddcc...
        ...cbbbbbc555bdddddc....
        ..ccbbbbbc55bddddddcc...
        ..ccbbbbbbcb55dddddbcc..
        ...cbbbbbb5555ddddddddcc
        ....cbbbbb555ddbdddddddc
        ....cccbbc55ddbbbddddcc.
        ...ccdddccddddbcbbccc...
        ...ccccccd555ddccc......
        ........cccccccc........
        `, SpriteKind.Boss)
    tiles.placeOnTile(Boss2, tiles.getTileLocation(14, 12))
    BossinitilizeFire = true
}
function CharacterTestCheat () {
    mySprite.ay = 0
    mySprite.vy = 0
    controller.moveSprite(mySprite, 200, 200)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.EnemeyProjectile, function (sprite, otherSprite) {
    otherSprite.destroy()
    CharacterStatusBar.value += -25
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (SwordInAction == true && BLAHAHHSJFFKDF == false) {
        otherSprite.destroy(effects.ashes, 200)
        GremlinKillCount += 1
    }
    timer.after(500, function () {
        if (SwordInAction == false) {
            CharacterStatusBar.value += -10
            BLAHAHHSJFFKDF = true
            animation.runImageAnimation(
            otherSprite,
            [img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .....fffc1111111f.......
                ...fc111cd1111111f......
                ...f1b1b1b1111dddf......
                ...fbfbffcf11fcddf......
                ......fcf111111bbf......
                .......ccbdb1b1fcf......
                .......fffbfbfdff.......
                ........ffffffff........
                ........fffffffffff.....
                .........fffffc111cf....
                .........fffff1b1b1f....
                ..........ffffbfbfbf....
                ...........ffff.........
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ....7.fd11111111df......
                ...7..fd11111111df......
                ...7..fd11111111df......
                ...7..fddd1111dddff.....
                ...77.fbdbfddfbdbfcf....
                ...777fcdcf11fcdcfbf....
                ....77fffbdb1bdffcf.....
                ....fcb1bcffffff........
                ....f1c1c1ffffff........
                ....fdfdfdfffff.........
                .....f.f.f..............
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd111111111f......
                ......fd11111111df......
                ......fd11111111df......
                ......fcdd1111ddcff.....
                .......fbcf11fcbfbbf....
                .......ffbdb1bdffff.....
                ........fcbfbfdf........
                ........ffffffff........
                ......ffffffffff........
                .....fcb1bcffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ......fdd111111ddf......
                ......fbdd1111dddf......
                ......fcdbfddfbdbf......
                .......fbcf11fcbfff.....
                .......ffb1111bcfbcf....
                ........fcdb1bdfbbbf....
                .......ffffffffffcf.....
                .....fcb1bcfffff........
                .....f1b1b1ffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                `],
            500,
            false
            )
            timer.after(300, function () {
                BLAHAHHSJFFKDF = false
            })
        }
    })
    pause(500)
})
let GremlinShoota1: Sprite = null
let FireBall: Sprite = null
let GremlinKillCount = 0
let Boss2: Sprite = null
let Gremlin32: Sprite = null
let Gremlin31: Sprite = null
let Gremlin22: Sprite = null
let Gremlin21: Sprite = null
let Gremlin12: Sprite = null
let Gremlin11: Sprite = null
let Princess: Sprite = null
let GremlinOnSticks = false
let AppleReminder = false
let Gremlin1Statusbar: StatusBarSprite = null
let CharacterArrow: Sprite = null
let CharacterStatusBar: StatusBarSprite = null
let SwordInAction = false
let SuperGremlinInvincible = false
let Gremlin41: Sprite = null
let TheWiseOne: Sprite = null
let mySprite: Sprite = null
let LegendaryChest: Sprite = null
let SuperGremlinVelo = 0
let BLAHAHHSJFFKDF = false
let SuperGremlinsAlive = false
let SwordUnlocked = false
let BossinitilizeFire = false
let JumpStatus = 0
let JumpCount = 0
let PrincessTraped = false
let BowUnlocked = false
let GremlinShootSpeed = 0
let key = 0
let row = 0
let column = 0
let AssistantAlive = false
column = 47
row = 11
key = 0
Level1()
Character()
princess()
SheildGremlins()
WiseOne()
GremlinShootSpeed = 1500
BowUnlocked = false
PrincessTraped = true
let moveOnX = 100
let moveOnY = 0
let moveWithButtonsAllowed = 1
JumpCount = 0
JumpStatus = 1
BossinitilizeFire = false
SwordUnlocked = false
let GremlinX = 41
SuperGremlinsAlive = false
let GremlinY = 48
BLAHAHHSJFFKDF = false
SuperGremlinVelo = 20
game.showLongText("The Princess is trapped! Restreieve her from the evil gremlims.", DialogLayout.Bottom)
timer.after(500, function () {
    tiles.setTileAt(tiles.getTileLocation(13, 46), assets.tile`myTile8`)
    tiles.setTileAt(tiles.getTileLocation(13, 47), assets.tile`myTile7`)
    scene.cameraShake(4, 500)
})
LegendaryChest = sprites.create(assets.tile`myTile42`, SpriteKind.Chest)
tiles.placeOnTile(LegendaryChest, tiles.getTileLocation(36, 49))
game.onUpdateInterval(5000, function () {
    if (BossinitilizeFire) {
        animation.runImageAnimation(
        Boss2,
        [img`
            ........................
            ........................
            ..........ccc...........
            .........cccc...........
            .....ccccccc..ccc.......
            ...cc555555cccccc.......
            ..c5555555555bcc........
            .c555555555555b..cc.....
            c555551ff555555bccc.....
            c55d55ff55555555bc......
            c5555555555555555b......
            .cbb31bb5555dd555b.cc...
            .c5333b555ddddd55dccc...
            .c533b55ddddddddddb.....
            .c5555dddbb55bdddddccc..
            ..ccccbbbb555bdddddccc..
            ...cdcbc5555bddddddcc...
            ....ccbc55bc5ddddddbcccc
            .....cbbcc5555dddddddddc
            .....ccbbb555ddbddddddc.
            .....cdcbc55ddbbbdddcc..
            ...ccdddccddddbcbbcc....
            ...ccccccd555ddccc......
            ........cccccccc........
            `,img`
            ............ccc.........
            .......cccccccc.........
            .....cc55555cc..cc......
            ....c555555555cccc......
            ...c55555555555bcc......
            ..c555551ff55555b..cc...
            ..c55d55ff5555555bccc...
            ..c55555555d55555bcc....
            ..c5555d5555d55555b.....
            ..cbbbb55555ddd555b.cc..
            ..c555d5555ddddd55dccc..
            ...c555dbbbdddbd5ddcc...
            ....cccbbbbb555bdddb....
            ....cbbbbbbc555bdddccc..
            ...cbbbbbbc555bddddcc...
            ...cbbbbbc555bdddddc....
            ..ccbbbbbc55bddddddcc...
            ..ccbbbbbbcb55dddddbcc..
            ...cbbbbbb5555ddddddddcc
            ....cbbbbb555ddbdddddddc
            ....cccbbc55ddbbbddddcc.
            ...ccdddccddddbcbbccc...
            ...ccccccd555ddccc......
            ........cccccccc........
            `,img`
            .............ccc........
            ........cccccccc........
            ......cc55555cc..cc.....
            .....c555555555cccc.....
            ....c55555555555bcc.....
            ...c555555ccb5555b.cc...
            ...c55d55c55555555bcc...
            ...c55555555dd5555bc....
            ...c5555d5555dd5555.....
            ...cbbbd555555dd555.cc..
            ...c555d555555ddd55ccc..
            ....c555d5555ddbd5dcc...
            ....cccbbbbb555bdddb....
            ...cbbbbbbbc555bdddccc..
            ..cbbbbbbbc555bddddcc...
            ..cbbbbbbc555bdddddc....
            .ccbbbbbbc55bddddddcc...
            .ccbbbbbbbcb55dddddbc...
            ..cbbbbbbb5555ddddddbc..
            ...cbbbbbb555ddbddddddc.
            ....cccbbc55ddbbbddddddc
            ...ccdddccddddbcbbcccccc
            ...ccccccd555ddccc......
            ........cccccccc........
            `,img`
            ........................
            ........................
            ........................
            ..........ccc...........
            .........cccc...........
            .....ccccccc..ccc.......
            ...cc555555cccccc.......
            ..c5555555555bcc........
            .c555555555555b..cc.....
            c555555ccb55555bccc.....
            c55d55c555555555bc......
            c5555555555555555b......
            .cbbb1bb5555dd555b.cc...
            .c533bbbb5ddddd55dcc....
            .c533bbbb5ddddddddbcc...
            .c533bbb55dddddddddcccc.
            .c5333bb5bb55bdddddcccdc
            .c5333b5bb555bddddddbddc
            .c53335b5555bddddddddddc
            ..c5555c55bb55dbddddddcc
            ...cccbccc55ddbbbddddcc.
            ....cdddccddddbcbbbcc...
            ....cccccd555ddcccc.....
            ........cccccccc........
            `,img`
            ........................
            ........................
            ........................
            ..........ccc...........
            .........cccc...........
            .....ccccccc..ccc.......
            ...cc555555cccccc.......
            ..c5555555555bcc........
            .c555555555555b..cc.....
            c555555ccb55555bccc.....
            c55d55c555555555bc......
            c5555555555555555b......
            .cbbb1bb5555dd555b.cc...
            .c533bbbb5ddddd55dcc....
            .c533bbbb5ddddddddbcc...
            .c5333bb55dddddddddcccc.
            .c5333b55bb55bdddddcccdc
            .c533355bb555bddddddbddc
            ..c5555b5555bddddddddddc
            ...cccbc55bb55dbddddddcc
            .....cbbcc55ddbbbddddcc.
            ....cdddccddddbcbbbcc...
            ....cccccd555ddcccc.....
            ........cccccccc........
            `,img`
            ........................
            ........................
            ........................
            ..........ccc...........
            .........cccc...........
            .....ccccccc..ccc.......
            ...cc555555cccccc.......
            ..c5555555555bcc........
            .c555555555555b..cc.....
            c555555ccb55555bccc.....
            c55d55c555555555bc......
            c5555555555555555b......
            .cbbb1bb5555dd555b.cc...
            .c533bbb55ddddd55dcc....
            .c5333bb5dddddddddbcc...
            .c5333b55ddddddddddcccc.
            .c533355dbb55bdddddcccdc
            ..c55555bb555bddddddbddc
            ...cccbb5555bddddddddddc
            .....cbc55bb55dbddddddcc
            .....cdbcc55ddbbbddddcc.
            ....cdddccddddbcbbbcc...
            ....cccccd555ddcccc.....
            ........cccccccc........
            `],
        500,
        false
        )
        FireBall = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 4 4 4 4 4 . . . . . . 
            . . . 4 4 4 5 5 5 d 4 4 4 4 . . 
            . . 4 d 5 d 5 5 5 d d d 4 4 . . 
            . . 4 5 5 1 1 1 d d 5 5 5 4 . . 
            . 4 5 5 5 1 1 1 5 1 1 5 5 4 4 . 
            . 4 d d 1 1 5 5 5 1 1 5 5 d 4 . 
            . 4 5 5 1 1 5 1 1 5 5 d d d 4 . 
            . 4 5 5 5 d 1 1 1 5 1 1 5 5 2 . 
            . 4 d 5 5 d 1 1 1 5 1 1 5 5 2 . 
            . . 4 4 d d 5 5 5 5 d d 5 4 . . 
            . . 4 4 2 4 d 5 5 d d 4 4 4 . . 
            . . . 4 4 2 2 4 4 4 2 4 4 . . . 
            . . . . . 4 4 4 4 4 4 . . . . . 
            . . . . . . . . . . . . . . . . 
            `, Boss2, 1, 1)
        FireBall.setKind(SpriteKind.Projectile)
        FireBall.follow(mySprite, 30)
    }
})
forever(function () {
    if (GremlinKillCount == 2) {
        tiles.setWallAt(tiles.getTileLocation(36, 36), false)
        tiles.setWallAt(tiles.getTileLocation(37, 36), false)
        tiles.setWallAt(tiles.getTileLocation(38, 36), false)
        tiles.setWallAt(tiles.getTileLocation(39, 36), false)
        tiles.setWallAt(tiles.getTileLocation(40, 36), false)
        tiles.setWallAt(tiles.getTileLocation(41, 36), false)
        tiles.setWallAt(tiles.getTileLocation(42, 36), false)
        tiles.setTileAt(tiles.getTileLocation(35, 36), sprites.dungeon.darkGroundWest)
        tiles.setTileAt(tiles.getTileLocation(36, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(37, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(38, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(39, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(40, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(41, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(42, 36), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(43, 36), sprites.dungeon.darkGroundEast)
    }
    if (GremlinKillCount == 4) {
        tiles.setWallAt(tiles.getTileLocation(36, 40), false)
        tiles.setWallAt(tiles.getTileLocation(37, 40), false)
        tiles.setWallAt(tiles.getTileLocation(38, 40), false)
        tiles.setWallAt(tiles.getTileLocation(39, 40), false)
        tiles.setWallAt(tiles.getTileLocation(40, 40), false)
        tiles.setWallAt(tiles.getTileLocation(41, 40), false)
        tiles.setWallAt(tiles.getTileLocation(42, 40), false)
        tiles.setTileAt(tiles.getTileLocation(35, 40), sprites.dungeon.darkGroundWest)
        tiles.setTileAt(tiles.getTileLocation(36, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(37, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(38, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(39, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(40, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(41, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(42, 40), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(43, 40), sprites.dungeon.darkGroundEast)
    }
    if (GremlinKillCount == 6) {
        game.showLongText("Oh no! Your sword has broken", DialogLayout.Bottom)
        tiles.setWallAt(tiles.getTileLocation(36, 44), false)
        tiles.setWallAt(tiles.getTileLocation(37, 44), false)
        tiles.setWallAt(tiles.getTileLocation(38, 44), false)
        tiles.setWallAt(tiles.getTileLocation(39, 44), false)
        tiles.setWallAt(tiles.getTileLocation(40, 44), false)
        tiles.setWallAt(tiles.getTileLocation(41, 44), false)
        tiles.setWallAt(tiles.getTileLocation(42, 44), false)
        tiles.setTileAt(tiles.getTileLocation(35, 44), sprites.dungeon.darkGroundWest)
        tiles.setTileAt(tiles.getTileLocation(36, 44), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(37, 44), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(38, 44), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(39, 44), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(40, 44), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(41, 44), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(42, 44), sprites.dungeon.darkGroundCenter)
        tiles.setTileAt(tiles.getTileLocation(43, 44), sprites.dungeon.darkGroundEast)
        mySprite.setImage(img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 8 8 8 8 2 f d 4 . . 
            . . 4 4 f 8 8 9 9 8 8 f 4 4 . . 
            . . . . . 8 9 8 8 9 8 . . . . . 
            . . . . . 8 8 . . 8 8 . . . . . 
            `)
        GremlinKillCount = 7
    }
})
forever(function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        JumpCount = 0
    }
})
forever(function () {
	
})
forever(function () {
    if (PrincessTraped) {
        Princess.say("Help!")
    } else {
    	
    }
})
game.onUpdateInterval(randint(GremlinShootSpeed, GremlinShootSpeed * 2.5), function () {
    if (SuperGremlinsAlive) {
        animation.runImageAnimation(
        Gremlin41,
        [img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......feee11eeef.......
            .....fffc1111111f.......
            ...fc111fff11fff1f......
            ...f1b1bf1f11f1fdf......
            ...fbfbf1ff11ff1ff......
            ......fcf111111fbf......
            .......ccbdb1b1fcf......
            .......fffbfbfdff.......
            ........ffffffff........
            ........fffffffffff.....
            .........fffffc111cf....
            .........fffff1b1b1f....
            ..........ffffbfbfbf....
            ...........ffff.........
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ....7.fd11111111df......
            ...7..fdeee11eeedf......
            ...7..fd11111111df......
            ...7..fdfff11fffdff.....
            ...77.fbf1fddf1fbfcf....
            ...777ff1ff11ff1ffbf....
            ....77fffbdb1bdffcf.....
            ....fcb1bcffffff........
            ....f1c1c1ffffff........
            ....fdfdfdfffff.........
            .....f.f.f..............
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fd111111df.......
            ......fdeee11eeedf......
            ......fd11111111df......
            ......fdfff11fffdf......
            ......fcf1f11f1fcff.....
            .......f1ff11ff1fbbf....
            .......ffbdb1bdffff.....
            ........fcbfbfdf........
            ........ffffffff........
            ......ffffffffff........
            .....fcb1bcffff.........
            ......ffbff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fd111111df.......
            ......fdeee11eeedf......
            ......fdd111111ddf......
            ......fbfff11fffdf......
            ......fcf1fddf1fbf......
            .......f1ff11ff1fff.....
            .......ffb1111bcfbcf....
            ........fcdb1bdfbbbf....
            .......ffffffffffcf.....
            .....fcb1bcfffff........
            .....f1b1b1ffff.........
            ......ffbff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        500,
        false
        )
        GremlinShoota1 = sprites.createProjectileFromSprite(img`
            . . a a a a d d a . . 
            . a a d d d d d a a . 
            a a a d a a a a a a a 
            a d d d d d a a a a a 
            a d d a a a a a d a a 
            a a a a d d d a d a a 
            a a d d a a d d d a a 
            a a d d d d d a d a a 
            a a d d a a d d a a a 
            . a a a d d d d d a . 
            . . a a a a a a a . . 
            `, Gremlin41, (mySprite.x - Gremlin41.x) * 1.5, (mySprite.y - Gremlin41.y) * 1.5)
        GremlinShoota1.setKind(SpriteKind.EnemeyProjectile)
    }
    if (SuperGremlinInvincible) {
        GremlinShootSpeed = GremlinShootSpeed * 2
    }
})
